# ==================================================================================================
#     Header
# ==================================================================================================

language: cpp
sudo: required
cache: apt

branches:
  only:
    - master
    - misc

# env:
#   # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
#   matrix:
#     - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    update: true
    # sources: &sources

# ==================================================================================================
#     Matrix
# ==================================================================================================

matrix:
  # exclude:
  #   - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:

    # ==========================================================================
    #     trusty
    # ==========================================================================

    # default
    - os: linux
      dist: trusty
      name: "trusty"

    # --------------------------------------------------------------------------
    #     trusty / gcc
    # --------------------------------------------------------------------------

    # Cannot use gcc 4.8 because of missing regex implementation.
    # - os: linux
    #   dist: trusty
    #   addons:
    #     apt:
    #       packages:
    #       - g++-4.8
    #   env: COMPILER=g++-4.8

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-4.9
      env: COMPILER=g++-4.9

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-5
      env: COMPILER=g++-5

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-6
      env: COMPILER=g++-6

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-7
      env: COMPILER=g++-7

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-8
      env: COMPILER=g++-8

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - g++-9
      env: COMPILER=g++-9

    # --------------------------------------------------------------------------
    #     trusty / clang
    # --------------------------------------------------------------------------

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - clang-3.5
      env: COMPILER=clang++-3.5 OPENMP=OFF

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - clang-3.6
      env: COMPILER=clang++-3.6 OPENMP=OFF

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - clang-3.7
      env: COMPILER=clang++-3.7 OPENMP=OFF

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - clang-3.8
          - libiomp-dev
      env: COMPILER=clang++-3.8

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - clang-3.9
          - libiomp-dev
      env: COMPILER=clang++-3.9

    # ==========================================================================
    #     xenial
    # ==========================================================================

    # default
    - os: linux
      dist: xenial
      name: "xenial"

    # --------------------------------------------------------------------------
    #     xenial / gcc
    # --------------------------------------------------------------------------

    # Cannot use gcc 4.8 because of missing regex implementation.
    # - os: linux
    #   dist: xenial
    #   addons:
    #     apt:
    #       packages:
    #       - g++-4.8
    #   env: COMPILER=g++-4.8

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-4.9
      env: COMPILER=g++-4.9

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-5
      env: COMPILER=g++-5

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-6
      env: COMPILER=g++-6

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-7
      env: COMPILER=g++-7

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-8
      env: COMPILER=g++-8

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-9
      env: COMPILER=g++-9

    # --------------------------------------------------------------------------
    #     xenial / clang
    # --------------------------------------------------------------------------

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.5
      env: COMPILER=clang++-3.5 OPENMP=OFF

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.6
      env: COMPILER=clang++-3.6 OPENMP=OFF

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.7
      env: COMPILER=clang++-3.7 OPENMP=OFF

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.8
          - libiomp-dev
      env: COMPILER=clang++-3.8

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.9
          - libiomp-dev
      env: COMPILER=clang++-3.9

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-4.0
          - libiomp-dev
      env: COMPILER=clang++-4.0

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-5.0
          - libiomp-dev
      env: COMPILER=clang++-5.0

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-6.0
          - libiomp-dev
      env: COMPILER=clang++-6.0

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-7.0
          - libiomp-dev
      env: COMPILER=clang++-7.0

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-8.0
          - libiomp-dev
      env: COMPILER=clang++-8.0

    # ==========================================================================
    #     bionic
    # ==========================================================================

    # default
    - os: linux
      dist: bionic
      name: "bionic"

    # --------------------------------------------------------------------------
    #     bionic / gcc
    # --------------------------------------------------------------------------

    - os: linux
      dist: bionic

    # ==========================================================================
    #     osx
    # ==========================================================================

    - os: osx
      osx_image: xcode8.3
      env: OPENMP=OFF

    - os: osx
      osx_image: xcode9.2
      env: OPENMP=OFF

# ==================================================================================================
#     Install
# ==================================================================================================

before_install:

  - echo "before_install"
  - echo ${TRAVIS_OS_NAME}

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      echo "adding toolchain"
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
    fi
  # The following Homebrew packages aren't linked by default, and need to be
  # prepended to the path explicitly.
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      echo "exporting llvm path"
      export PATH="$(brew --prefix llvm)/bin:$PATH";
    fi

# ==================================================================================================
#     Script
# ==================================================================================================

script:
  - echo "script"

  # List available gcc and clang versions
  # - apt-cache pkgnames g++ | sort
  # - apt-cache pkgnames clang | sort

  - echo -e "\e[1;31mTravis environment\e[0m"
  - echo "PATH = $PATH"
  - echo "HOME = $HOME"
  - echo "Compiler"
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - ${COMPILER} --version
  - cmake --version

  - export GENESIS_DEBUG=1
  - mkdir build
  - cd build

  - export GENESIS_USE_OPENMP=ON
  - if [[ "${OPENMP}" == "OFF" ]]; then export GENESIS_USE_OPENMP=OFF; fi

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DGENESIS_USE_OPENMP=$GENESIS_USE_OPENMP ..
  - make
  - cd ..
  - ./bin/test/genesis_tests
