language: cpp
sudo: required
cache: apt

branches:
  only:
    - master
    - misc

# env:
#   # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
#   matrix:
#     - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  # exclude:
  #   - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - g++-7
      env: COMPILER=g++-7

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
          - clang-3.6
      env: COMPILER=clang++-3.6 OPENMP=OFF

    - os: osx
      osx_image: xcode9.2
      env: OPENMP=OFF

    - os: osx
      osx_image: xcode8.3
      env: OPENMP=OFF


before_install:
  - echo "PATH = $PATH"
  - echo "HOME = $HOME"

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
    fi

script:
  - export GENESIS_DEBUG=1
  - mkdir build
  - cd build

  - export GENESIS_USE_OPENMP=ON
  - if [[ "${OPENMP}" == "OFF" ]]; then export GENESIS_USE_OPENMP=OFF; fi

  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DGENESIS_USE_OPENMP=$GENESIS_USE_OPENMP ..
  - make
  - cd ..
  - ./bin/test/genesis_tests
